apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: kwetteracr.azurecr.io/gateway:latest
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: registry
      imagePullSecrets:
        - name: kwettersecret
      hostname: gateway
      restartPolicy: Always
