server:
  port: 8085

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: 8083
    preferIpAddress: true
    hostname: host.docker.internal
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
    healthcheck:
      enabled: true
    fetch-registry: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: userService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/{segment}
        - id: viewService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/view/{segment}
        - id: searchService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/search/{segment}
        - id: authenticationService
          uri: tcp://USERSERVICE
          predicates:
            - Path=/authenticate/{segment}
        - id: followService
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/follow/{segment}
        - id: postService
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/{segment}
        - id: postAllService
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/getallfromuser/{segment}
        - id: feedService
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/feed/{segment}

